#!/usr/bin/env bash
#
# Rebuild and restart the supply-chain emulator on its own dsh profile.
#
# Reloads all three layers the emulator spans, because a change to any one of
# them is invisible until its artifact is rebuilt AND the host process restarts:
#
#   1. backend   packages/supply-chain/*        the seam, the ISOMORPH provider, the agent tools
#   2. remote    lib/typert.{host,remote-client} the generated browser-to-host RPC surface
#   3. ui        packages/client/ui-supply-chain the center-column panel, plus ui-geo-earth
#                                                for the ctx.earthOverlays globe face
#
# The `supply-chain` profile carries the machine-specific simulator paths as a
# patch layer, so the shipped bundle keeps the provider dormant and no absolute
# path is committed. Re-running this script is safe and idempotent.
#
# Usage:
#   ./restart-supply-chain.sh                 rebuild, then boot the profile
#   ./restart-supply-chain.sh --no-build      restart only (skip the rebuilds)
#
# Environment:
#   DSH_ISOMORPH_ROOT     ISOMORPH demo checkout holding simulator/demo_simulator.py
#   DSH_ISOMORPH_PYTHON   interpreter that can import that simulator
#   DSH_SUPPLY_PROFILE    profile name (default: supply-chain)
#   DSH_PORT              port to free before booting (default: 3080)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

ISOMORPH_ROOT="${DSH_ISOMORPH_ROOT:-/Volumes/ExternalSSD/geoagent/ISOMORPH/demo}"
ISOMORPH_PYTHON="${DSH_ISOMORPH_PYTHON:-/Volumes/ExternalSSD/geoagent/ISOMORPH/.venv/bin/python}"
PROFILE="${DSH_SUPPLY_PROFILE:-supply-chain}"
PORT="${DSH_PORT:-3080}"
PROFILE_DIR="${DSH_HOME:-$HOME/.dsh}/profiles/$PROFILE"

BUILD=1
for arg in "$@"; do
  case "$arg" in
    --no-build) BUILD=0 ;;
    *) echo "unknown flag: $arg (accepts --no-build)" >&2; exit 2 ;;
  esac
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# The simulator is an external checkout, so a missing or unmounted one is the
# likeliest failure. Report it here rather than as a panel error after boot.
step "Checking the ISOMORPH simulator"
if [[ ! -f "$ISOMORPH_ROOT/simulator/demo_simulator.py" ]]; then
  echo "no simulator at $ISOMORPH_ROOT/simulator/demo_simulator.py" >&2
  echo "set DSH_ISOMORPH_ROOT to the ISOMORPH demo checkout (is the volume mounted?)" >&2
  exit 1
fi
if [[ ! -x "$ISOMORPH_PYTHON" ]]; then
  echo "no usable interpreter at $ISOMORPH_PYTHON; set DSH_ISOMORPH_PYTHON" >&2
  exit 1
fi
"$ISOMORPH_PYTHON" -c "import sys; sys.path.insert(0, '$ISOMORPH_ROOT'); import simulator.demo_simulator" \
  || { echo "that interpreter cannot import the simulator (missing dependencies?)" >&2; exit 1; }
echo "simulator OK: $ISOMORPH_ROOT"

if [[ $BUILD -eq 1 ]]; then
  # The seam's host build regenerates lib/typert.*; the browser calls the
  # generated client, so a changed @Remote signature is stale until this runs.
  step "Building backend + remote (supply-chain seam, provider, tools)"
  pnpm exec tsdown --env.DSH_BUILD_FACE host \
    --filter @deepseek-ai/dsh-supply-chain \
    --filter @deepseek-ai/dsh-supply-chain-isomorph \
    --filter @deepseek-ai/dsh-tool-supply-chain

  # The plugin registry serves lib/client.js, never the sources. ui-geo-earth
  # is included because it publishes the ctx.earthOverlays face the panel draws
  # the network through; without it the panel's fiber waits forever.
  step "Building UI (ui-supply-chain, ui-geo-earth)"
  pnpm --filter @deepseek-ai/dsh-client-ui-supply-chain bundle
  pnpm --filter @deepseek-ai/dsh-client-ui-geo-earth bundle
fi

step "Writing the $PROFILE profile"
# This script owns its profile and rewrites both files on every run. Pointing it
# at a profile someone curated (the `web` profile carries an installed plugin
# list) would silently discard that, so refuse unless the target is already ours.
if [[ -f "$PROFILE_DIR/package.json" ]] \
   && ! grep -q '"dshEmulatorProfile": true' "$PROFILE_DIR/package.json"; then
  echo "$PROFILE_DIR already exists and was not created by this script" >&2
  echo "refusing to overwrite it; pick another DSH_SUPPLY_PROFILE name" >&2
  exit 1
fi
mkdir -p "$PROFILE_DIR"

# Bundle list only; plugin rows come from the bundles' own patch layers.
cat > "$PROFILE_DIR/package.json" <<EOF
{
  "name": "dsh-profile-$PROFILE",
  "private": true,
  "dependencies": {},
  "dshEmulatorProfile": true,
  "dsh": {
    "profile": {
      "bundles": [
        "@deepseek-ai/dsh-base",
        "@deepseek-ai/dsh-web-app"
      ]
    }
  },
  "packageManager": "pnpm@11.7.0"
}
EOF

# The user layer, applied after every bundle layer: it enables the provider the
# base bundle ships dormant and hands it this machine's paths.
cat > "$PROFILE_DIR/cordis.patch.yml" <<EOF
# Generated by restart-supply-chain.sh — edits are overwritten on the next run.
- id: supply-chain-isomorph
  disabled: false
  config:
    pythonBin: $ISOMORPH_PYTHON
    simulatorRoot: $ISOMORPH_ROOT
EOF
echo "profile written: $PROFILE_DIR"

step "Freeing port $PORT"
# A live listener keeps serving its old host code, which is the whole reason a
# rebuild alone does not take effect.
if pids="$(lsof -ti "tcp:$PORT" 2>/dev/null)" && [[ -n "$pids" ]]; then
  echo "stopping: $pids"
  kill $pids 2>/dev/null || true
  for _ in $(seq 1 40); do
    lsof -ti "tcp:$PORT" >/dev/null 2>&1 || break
    sleep 0.25
  done
  if lsof -ti "tcp:$PORT" >/dev/null 2>&1; then
    echo "still listening; sending SIGKILL"
    kill -9 $(lsof -ti "tcp:$PORT") 2>/dev/null || true
    sleep 1
  fi
else
  echo "nothing listening on $PORT"
fi

step "Booting dsh --profile $PROFILE on port $PORT"
echo "open http://127.0.0.1:$PORT and pick the 'Supply chain' tab in a session"
exec pnpm dsh --profile "$PROFILE" --port "$PORT" --no-open
